
swagger: '2.0'
info:
  description: Configuration for Managed Device resource.
  version: 'v2'
  title: managed_device
host: 'adm.cloud.com'
schemes:
 - https
# tags are used for organizing operations
tags:
  - name: managed_device
    description: Managed Device
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  UserSecurity:
    type: basic
security:
  - UserSecurity: []
parameters:
  idParam:
   name: id
   in: path
   type: string
   description: Id is system generated key for all the managed devices
   required: true
  authParam:
      in: header
      name: Authorization
      type: string
      required: true
      description: Session Id for authentication.Should be mentioned in the format CwsAuth bearer=sessionIdValue
  cloudParam:
      in: header
      name: isCloud
      type: string
      required: true
      description: set the value to true in case of Cloud services, false for on-prem deployment
paths:
  /massvc/{customerid}/nitro/v2/config/managed_device:
    get:
      tags:
        - managed_device
      summary: GET all managed_device
      operationId: getall_managed_device
      description: Use this operation to get managed devices
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: customerid
          type: string
          required: true
          description: Customer Id of the user
        - in: header
          name: Authorization
          type: string
          required: true
          description: Session Id for authentication.Should be mentioned in the format CwsAuth bearer=sessionIdValue
        - in: header
          name: isCloud
          type: string
          required: true
          description: set the value to true in case of Cloud services, false for on-prem deployment
        - in: query
          name: filter
          type: string
          required: false
          description: "Use this query-parameter to get the filtered set of vm_device resources configured on the system. You can set a filter on any property of the resource.Example:  property-name1:property-value1 "
        - in: query
          name: pagesize
          type: integer
          required: false
          description: Use this query-parameter to get the managed_device resources in chunks.To be used along with pageno query parameter.
        - in: query
          name: pageno
          type: integer
          required: false
          description: Use this query-parameter to get the managed_device resources in chunks.To be used along with pagesize query parameter.
        - in: query
          name: count
          type: string
          required: false
          description: Use this query-parameter to get the count of managed_device resources.
          enum:
            - yes
      responses:
        200:
          description:  for managed_device
          schema:
              $ref: '#/definitions/getmanaged_devicesResponse'
        400:
          description: Bad input parameter
          schema:
              $ref: '#/definitions/Error'
        401:
          description: Failed Authentication
          schema:
              $ref: '#/definitions/Error'
        403:
          description: Unauthorized
          schema:
              $ref: '#/definitions/Error'
        404:
          description: Item not found
          schema:
              $ref: '#/definitions/Error'
        409:
          description: Resource Conflict
          schema:
              $ref: '#/definitions/Error'
        500:
          description: Server Error
          schema:
              $ref: '#/definitions/Error'
        504:
          description: Gateway Timeout
          schema:
              $ref: '#/definitions/Error'

    post:
      tags:
        - managed_device
      summary: POST operation for managed_device
      operationId: post_managed_device
      description: POST operation for managed_device
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: customerid
          type: string
          required: true
          description: Customer Id of the user
        - in: header
          name: Authorization
          type: string
          required: true
          description: Session Id for authentication.Should be mentioned in the format CwsAuth bearer=sessionIdValue
        - in: header
          name: isCloud
          type: string
          required: true
          description: set the value to true in case of Cloud services, false for on-prem deployment
        - in: query
          name: onerror
          description: Use this parameter to set the onerror status for nitro request. Applicable only for bulk requests.
          required: false
          type: string
          default: CONTINUE
          enum:
            - EXIT
            - CONTINUE
        - in: query
          name: action
          type: string
          required: false
          enum: [add_device]
          description: >
            actions:
              * `add_device` - Use this operation to add managed device.Required properties are: ip_address,profile_name.Optional params: agent_id,file_name.For BLX ADC HA,device_host_ip,peer_device_ip,peer_host_ip are the additional required params

        - in: body
          name: managed_device
          description: managed_device object
          schema:
              $ref: '#/definitions/addmanaged_deviceRequest'
      responses:
        200:
          description: add_device for managed_device
          schema:
              $ref: '#/definitions/addmanaged_deviceResponse'
        400:
          description: Bad input parameter
          schema:
              $ref: '#/definitions/Error'
        401:
          description: Failed Authentication
          schema:
              $ref: '#/definitions/Error'
        403:
          description: Unauthorized
          schema:
              $ref: '#/definitions/Error'
        404:
          description: Item not found
          schema:
              $ref: '#/definitions/Error'
        409:
          description: Resource Conflict
          schema:
              $ref: '#/definitions/Error'
        500:
          description: Server Error
          schema:
              $ref: '#/definitions/Error'
        504:
          description: Gateway Timeout
          schema:
              $ref: '#/definitions/Error'

  /massvc/{customerid}/nitro/v2/config/managed_device/{id}:
    get:
      tags:
        - managed_device
      summary: GET by key for managed_device
      operationId: getbykey_managed_device
      description: Use this operation to get managed devices
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/idParam'
        - in: path
          name: customerid
          type: string
          required: true
          description: Customer Id of the user
        - in: header
          name: Authorization
          type: string
          required: true
          description: Session Id for authentication.Should be mentioned in the format CwsAuth bearer=sessionIdValue
        - in: header
          name: isCloud
          type: string
          required: true
          description: set the value to true in case of Cloud services, false for on-prem deployment
      responses:
        200:
          description: add_device for managed_device
          schema:
              $ref: '#/definitions/getmanaged_deviceResponse'
        400:
          description: Bad input parameter
          schema:
              $ref: '#/definitions/Error'
        401:
          description: Failed Authentication
          schema:
              $ref: '#/definitions/Error'
        403:
          description: Unauthorized
          schema:
              $ref: '#/definitions/Error'
        404:
          description: Item not found
          schema:
              $ref: '#/definitions/Error'
        409:
          description: Resource Conflict
          schema:
              $ref: '#/definitions/Error'
        500:
          description: Server Error
          schema:
              $ref: '#/definitions/Error'
        504:
          description: Gateway Timeout
          schema:
              $ref: '#/definitions/Error'

    post:
      tags:
        - managed_device
      summary: POST operation with actions for managed_device
      operationId: post_managed_device_actions
      description: POST operation with actions for managed_device
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/idParam'
        - in: path
          name: customerid
          type: string
          required: true
          description: Customer Id of the user
        - in: header
          name: Authorization
          type: string
          required: true
          description: Session Id for authentication.Should be mentioned in the format CwsAuth bearer=sessionIdValue
        - in: header
          name: isCloud
          type: string
          required: true
          description: set the value to true in case of Cloud services, false for on-prem deployment
        - in: query
          name: action
          type: string
          required: true
          enum: [annotate,allocate_vcpu_license,allocate_license,mastools_restart]
          description: >
            actions:
              * `annotate` - Use this operation to annotate managed device.Use description property to annotate
              * `allocate_vcpu_license` - Use this operation to allocate/release vpcu licenses
              * `allocate_license` - Use this operation to allocate/release licenses
              * `mastools_restart` - Use this operation to restart of mastools device

        - in: body
          name: managed_device
          description: managed_device object
          schema:
              $ref: '#/definitions/addmanaged_deviceRequest'
      responses:
        200:
          description: mastools_restart for managed_device
          schema:
              $ref: '#/definitions/addmanaged_deviceResponse'
        400:
          description: Bad input parameter
          schema:
              $ref: '#/definitions/Error'
        401:
          description: Failed Authentication
          schema:
              $ref: '#/definitions/Error'
        403:
          description: Unauthorized
          schema:
              $ref: '#/definitions/Error'
        404:
          description: Item not found
          schema:
              $ref: '#/definitions/Error'
        409:
          description: Resource Conflict
          schema:
              $ref: '#/definitions/Error'
        500:
          description: Server Error
          schema:
              $ref: '#/definitions/Error'
        504:
          description: Gateway Timeout
          schema:
              $ref: '#/definitions/Error'

    put:
      tags:
        - managed_device
      summary: PUT for managed_device
      operationId: putbykey_managed_device
      description: Use this operation to update managed device
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/idParam'
        - in: path
          name: customerid
          type: string
          required: true
          description: Customer Id of the user
        - in: header
          name: Authorization
          type: string
          required: true
          description: Session Id for authentication.Should be mentioned in the format CwsAuth bearer=sessionIdValue
        - in: header
          name: isCloud
          type: string
          required: true
          description: set the value to true in case of Cloud services, false for on-prem deployment
        - in: body
          name: managed_device
          description: managed_device object
          schema:
              $ref: '#/definitions/modifymanaged_deviceRequest'
      responses:
        200:
          description: mastools_restart for managed_device
          schema:
              $ref: '#/definitions/modifymanaged_deviceResponse'
        400:
          description: Bad input parameter
          schema:
              $ref: '#/definitions/Error'
        401:
          description: Failed Authentication
          schema:
              $ref: '#/definitions/Error'
        403:
          description: Unauthorized
          schema:
              $ref: '#/definitions/Error'
        404:
          description: Item not found
          schema:
              $ref: '#/definitions/Error'
        409:
          description: Resource Conflict
          schema:
              $ref: '#/definitions/Error'
        500:
          description: Server Error
          schema:
              $ref: '#/definitions/Error'
        504:
          description: Gateway Timeout
          schema:
              $ref: '#/definitions/Error'

    delete:
      tags:
        - managed_device
      summary: Delete for managed_device
      operationId: deletebykey_managed_device
      description: Use this operation to delete managed device
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/idParam'
        - in: path
          name: customerid
          type: string
          required: true
          description: Customer Id of the user
        - in: header
          name: Authorization
          type: string
          required: true
          description: Session Id for authentication.Should be mentioned in the format CwsAuth bearer=sessionIdValue
        - in: header
          name: isCloud
          type: string
          required: true
          description: set the value to true in case of Cloud services, false for on-prem deployment
      responses:
        204:
          description: mastools_restart for managed_device
        400:
          description: Bad input parameter
          schema:
              $ref: '#/definitions/Error'
        401:
          description: Failed Authentication
          schema:
              $ref: '#/definitions/Error'
        403:
          description: Unauthorized
          schema:
              $ref: '#/definitions/Error'
        404:
          description: Item not found
          schema:
              $ref: '#/definitions/Error'
        409:
          description: Resource Conflict
          schema:
              $ref: '#/definitions/Error'
        500:
          description: Server Error
          schema:
              $ref: '#/definitions/Error'
        504:
          description: Gateway Timeout
          schema:
              $ref: '#/definitions/Error'

  /massvc/{customerid}/nitro/v2/upload/managed_device:
    post:
      tags:
        - managed_device
      summary: Upload operation for managed_device
      operationId: upload_managed_device
      description: Use this operation to upload build file
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - in: path
          name: customerid
          type: string
          required: true
          description: Customer Id of the user
        - in: header
          name: Authorization
          type: string
          required: true
          description: Session Id for authentication.Should be mentioned in the format CwsAuth bearer=sessionIdValue
        - in: header
          name: isCloud
          type: string
          required: true
          description: set the value to true in case of Cloud services, false for on-prem deployment
        - in: formData
          name: managed_device
          description: managed_device file
          type: file
          required: true
      responses:
        200:
          description: Successful upload for managed_device
          schema:
              $ref: '#/definitions/Done'
        400:
          description: Bad input parameter
          schema:
              $ref: '#/definitions/Error'
        401:
          description: Failed Authentication
          schema:
              $ref: '#/definitions/Error'
        403:
          description: Unauthorized
          schema:
              $ref: '#/definitions/Error'
        404:
          description: Item not found
          schema:
              $ref: '#/definitions/Error'
        409:
          description: Resource Conflict
          schema:
              $ref: '#/definitions/Error'
        500:
          description: Server Error
          schema:
              $ref: '#/definitions/Error'
        504:
          description: Gateway Timeout
          schema:
              $ref: '#/definitions/Error'

definitions:
  addmanaged_deviceRequest:
    type: object
    required:
      - managed_device
    properties:
      managed_device:
        $ref: '#/definitions/managed_device_readwrite'
    title: addmanaged_deviceRequest
    example:
      managed_device:
        std_bw_config: "0"
        description: "Provisioned on 10 Jan 18"
        vcpu_config: "0"
        ent_bw_config: "0"
        datacenter_id: "ec523330-b31e-4831-8c8c-cdb5b9ce4599"
        instance_config: "0"
        is_managed: "true"
        profile_name: "ns_nsroot_profile"
        servicepackage: "svcpkg1"
        license_edition: "Platinum"
        isolation_policy: "shared"
        ip_address: "10.102.40.60"
        plt_bw_config: "0"
        agent_id: "38f867d1-3d10-4bfa-8498-604a57e67bc4"
        peer_device_ip: "10.102.40.26"
        file_name: "instancelist.txt"
        file_location_path: "C:\\myfiles"
        peer_host_device_ip: "10.102.40.27"
        device_host_ip: "10.102.40.25"
        entity_tag: "[{\"prop_key\":\"country\",\"prop_value\":\"US\"},{\"prop_key\":\"Labcode\",\"prop_value\":\"FtLAB23005\"}]}"

  addmanaged_deviceResponse:
    type: object
    required:
      - managed_device
    properties:
      managed_device:
        $ref: '#/definitions/managed_device'
    title: addmanaged_deviceResponse
    example:
      managed_device:
        instance_classifier: "0"
        subnet_id: "string_value"
        manufacturedate: " 2/17/2009"
        is_grace: "false"
        hostname: "ADC16_Devlab"
        std_bw_config: "0"
        gateway_deployment: "false"
        is_fips_pooled_license_type: "0"
        gateway_ipv6: "FE80::1"
        ha_master_state: "Primary"
        instance_available: "0"
        vpc_id: "string_value"
        device_finger_print: "string_value"
        instance_state: "Up"
        httpquerywithurl: "ENABLED"
        region: "string_value"
        reason: "Authentication failure"
        ent_bw_available: "0"
        description: "Provisioned on 10 Jan 18"
        is_autoscale_group: "false"
        geo_support: "false"
        is_pooled_license: "false"
        upsince: "Fri Jan 10 09:44:56 2019"
        sslvpn_config: "0"
        security_group: "string_value"
        private_dns: "string_value"
        user_driven: "true"
        zone: "string_value"
        mastools_version: "13.0-49.32"
        model_id: "100000"
        sysservices: "72"
        ent_bw_total: "0"
        vcpu_config: "0"
        tenant_id: "7ed7946f-4af7-11e9-99d2-b6fe81a85d18"
        device_uuid: "1fa7946f-4af7-11e9-99d2-b6fe81a85d08"
        do_config: "true"
        autoprovisioned: "false"
        ent_bw_config: "0"
        datacenter_id: "ec523330-b31e-4831-8c8c-cdb5b9ce4599"
        host_id: "b6fe81a85d08"
        version: "NetScaler NS12.1: Build 54.13.nc"
        instance_config: "0"
        is_managed: "true"
        discovery_time: "number_value"
        instance_mode: "Primary"
        public_dns: "string_value"
        instance_total: "0"
        is_ha_configured: "true"
        trust_id: "2ca7946f-4af7-11e9-99d2-b6fe81a85d09"
        ipv4_address: "10.102.40.60"
        instance_type: "string_value"
        profile_name: "ns_nsroot_profile"
        seq_no: "number_value"
        std_bw_available: "0"
        sysid: "450000"
        servicepackage: "svcpkg1"
        last_updated_time: "number_value"
        cloud: "string_value"
        encoded_serialnumber: "98310000cb254307ee78"
        instance_unique_id: "38f867d1-3d10-4bfa-8498-604a57e67bc4"
        plt_bw_total: "0"
        uptime: "14400"
        private_ip: "string_value"
        id: "c970e730-6bc5-44c2-a2bf-8dd1382ffb5f"
        mgmt_ip_address: "10.102.40.59"
        ipv6_address: "2001:cdba:0000:0000:0000:0000:3257:9652"
        partition_id: "5"
        license_edition: "Platinum"
        cpu_license_type: "0"
        cpufrequncy: "1904"
        plt_bw_available: "0"
        device_family: "ns"
        location: "DC12"
        template_interval: "60"
        contactperson: "jane"
        ha_sync: "ENABLED"
        public_ip: "string_value"
        ha_ip_address: "10.102.40.61"
        bmcrevision: "-NA-"
        type: "nsvpx"
        status: "Instance not reachable"
        internal_annotation: "mark_for_delete"
        systemname: "NetScalerBLR1"
        geo_location: "string_value"
        node_id: "a2f7a85e-f388-4d2d-ae0e-646b4f66797e"
        isolation_policy: "shared"
        ip_address: "10.102.40.60"
        provision_request_id: "48f867d1-3d10-4bfa-8498-604a57e67bc5"
        ping_state: "integer_value"
        httpxforwardedfor: "ENABLED"
        std_bw_total: "0"
        display_name: "10.102.40.60-10.102.40.61"
        ami_id: "string_value"
        httpcookie: "ENABLED"
        plt_bw_config: "0"
        partition_name: "p1"
        agent_id: "38f867d1-3d10-4bfa-8498-604a57e67bc4"
        sslvpn_total: "0"
        serialnumber: "HE2H91SCZ6"
        peer_device_ip: "10.102.40.26"
        parent_inventory: "boolean_value"
        profile_password: "nsroot"
        register_failed_device: "false"
        act_id: "fce5b825-9217-4e58-b80c-48cfe8f0c6b3"
        file_name: "instancelist.txt"
        do_instance_config: "true"
        profile_username: "nsroot"
        default_password: "string_value"
        file_location_path: "C:\\myfiles"
        sync_operation: "true"
        peer_host_device_ip: "10.102.40.27"
        device_host_ip: "10.102.40.25"
        tr_task_id: "string_value"
        entity_tag: "[{\"prop_key\":\"country\",\"prop_value\":\"US\"},{\"prop_key\":\"Labcode\",\"prop_value\":\"FtLAB23005\"}]}"
        force_password_change: "false"

  getmanaged_deviceResponse:
    type: object
    required:
      - managed_device
    properties:
      managed_device:
        $ref: '#/definitions/managed_device'
    title: getmanaged_deviceResponse
    example:
      managed_device:
        instance_classifier: "0"
        subnet_id: "string_value"
        manufacturedate: " 2/17/2009"
        is_grace: "false"
        hostname: "ADC16_Devlab"
        std_bw_config: "0"
        gateway_deployment: "false"
        is_fips_pooled_license_type: "0"
        gateway_ipv6: "FE80::1"
        ha_master_state: "Primary"
        instance_available: "0"
        vpc_id: "string_value"
        device_finger_print: "string_value"
        instance_state: "Up"
        httpquerywithurl: "ENABLED"
        region: "string_value"
        reason: "Authentication failure"
        ent_bw_available: "0"
        description: "Provisioned on 10 Jan 18"
        is_autoscale_group: "false"
        geo_support: "false"
        is_pooled_license: "false"
        upsince: "Fri Jan 10 09:44:56 2019"
        sslvpn_config: "0"
        security_group: "string_value"
        private_dns: "string_value"
        user_driven: "true"
        zone: "string_value"
        mastools_version: "13.0-49.32"
        model_id: "100000"
        sysservices: "72"
        ent_bw_total: "0"
        vcpu_config: "0"
        tenant_id: "7ed7946f-4af7-11e9-99d2-b6fe81a85d18"
        device_uuid: "1fa7946f-4af7-11e9-99d2-b6fe81a85d08"
        do_config: "true"
        autoprovisioned: "false"
        ent_bw_config: "0"
        datacenter_id: "ec523330-b31e-4831-8c8c-cdb5b9ce4599"
        host_id: "b6fe81a85d08"
        version: "NetScaler NS12.1: Build 54.13.nc"
        instance_config: "0"
        is_managed: "true"
        discovery_time: "number_value"
        instance_mode: "Primary"
        public_dns: "string_value"
        instance_total: "0"
        is_ha_configured: "true"
        trust_id: "2ca7946f-4af7-11e9-99d2-b6fe81a85d09"
        ipv4_address: "10.102.40.60"
        instance_type: "string_value"
        profile_name: "ns_nsroot_profile"
        seq_no: "number_value"
        std_bw_available: "0"
        sysid: "450000"
        servicepackage: "svcpkg1"
        last_updated_time: "number_value"
        cloud: "string_value"
        encoded_serialnumber: "98310000cb254307ee78"
        instance_unique_id: "38f867d1-3d10-4bfa-8498-604a57e67bc4"
        plt_bw_total: "0"
        uptime: "14400"
        private_ip: "string_value"
        id: "c970e730-6bc5-44c2-a2bf-8dd1382ffb5f"
        mgmt_ip_address: "10.102.40.59"
        ipv6_address: "2001:cdba:0000:0000:0000:0000:3257:9652"
        partition_id: "5"
        license_edition: "Platinum"
        cpu_license_type: "0"
        cpufrequncy: "1904"
        plt_bw_available: "0"
        device_family: "ns"
        location: "DC12"
        template_interval: "60"
        contactperson: "jane"
        ha_sync: "ENABLED"
        public_ip: "string_value"
        ha_ip_address: "10.102.40.61"
        bmcrevision: "-NA-"
        type: "nsvpx"
        status: "Instance not reachable"
        internal_annotation: "mark_for_delete"
        systemname: "NetScalerBLR1"
        geo_location: "string_value"
        node_id: "a2f7a85e-f388-4d2d-ae0e-646b4f66797e"
        isolation_policy: "shared"
        ip_address: "10.102.40.60"
        provision_request_id: "48f867d1-3d10-4bfa-8498-604a57e67bc5"
        ping_state: "integer_value"
        httpxforwardedfor: "ENABLED"
        std_bw_total: "0"
        display_name: "10.102.40.60-10.102.40.61"
        ami_id: "string_value"
        httpcookie: "ENABLED"
        plt_bw_config: "0"
        partition_name: "p1"
        agent_id: "38f867d1-3d10-4bfa-8498-604a57e67bc4"
        sslvpn_total: "0"
        serialnumber: "HE2H91SCZ6"
        peer_device_ip: "10.102.40.26"
        parent_inventory: "boolean_value"
        profile_password: "nsroot"
        register_failed_device: "false"
        act_id: "fce5b825-9217-4e58-b80c-48cfe8f0c6b3"
        file_name: "instancelist.txt"
        do_instance_config: "true"
        profile_username: "nsroot"
        default_password: "string_value"
        file_location_path: "C:\\myfiles"
        sync_operation: "true"
        peer_host_device_ip: "10.102.40.27"
        device_host_ip: "10.102.40.25"
        tr_task_id: "string_value"
        entity_tag: "[{\"prop_key\":\"country\",\"prop_value\":\"US\"},{\"prop_key\":\"Labcode\",\"prop_value\":\"FtLAB23005\"}]}"
        force_password_change: "false"

  getmanaged_devicesResponse:
    type: object
    required:
      - managed_device
    properties:
      managed_device:
        type: array
        items:
          $ref: '#/definitions/managed_device'
    title: getmanaged_devicesResponse
    example:
      managed_device:
        instance_classifier: "0"
        subnet_id: "string_value"
        manufacturedate: " 2/17/2009"
        is_grace: "false"
        hostname: "ADC16_Devlab"
        std_bw_config: "0"
        gateway_deployment: "false"
        is_fips_pooled_license_type: "0"
        gateway_ipv6: "FE80::1"
        ha_master_state: "Primary"
        instance_available: "0"
        vpc_id: "string_value"
        device_finger_print: "string_value"
        instance_state: "Up"
        httpquerywithurl: "ENABLED"
        region: "string_value"
        reason: "Authentication failure"
        ent_bw_available: "0"
        description: "Provisioned on 10 Jan 18"
        is_autoscale_group: "false"
        geo_support: "false"
        is_pooled_license: "false"
        upsince: "Fri Jan 10 09:44:56 2019"
        sslvpn_config: "0"
        security_group: "string_value"
        private_dns: "string_value"
        user_driven: "true"
        zone: "string_value"
        mastools_version: "13.0-49.32"
        model_id: "100000"
        sysservices: "72"
        ent_bw_total: "0"
        vcpu_config: "0"
        tenant_id: "7ed7946f-4af7-11e9-99d2-b6fe81a85d18"
        device_uuid: "1fa7946f-4af7-11e9-99d2-b6fe81a85d08"
        do_config: "true"
        autoprovisioned: "false"
        ent_bw_config: "0"
        datacenter_id: "ec523330-b31e-4831-8c8c-cdb5b9ce4599"
        host_id: "b6fe81a85d08"
        version: "NetScaler NS12.1: Build 54.13.nc"
        instance_config: "0"
        is_managed: "true"
        discovery_time: "number_value"
        instance_mode: "Primary"
        public_dns: "string_value"
        instance_total: "0"
        is_ha_configured: "true"
        trust_id: "2ca7946f-4af7-11e9-99d2-b6fe81a85d09"
        ipv4_address: "10.102.40.60"
        instance_type: "string_value"
        profile_name: "ns_nsroot_profile"
        seq_no: "number_value"
        std_bw_available: "0"
        sysid: "450000"
        servicepackage: "svcpkg1"
        last_updated_time: "number_value"
        cloud: "string_value"
        encoded_serialnumber: "98310000cb254307ee78"
        instance_unique_id: "38f867d1-3d10-4bfa-8498-604a57e67bc4"
        plt_bw_total: "0"
        uptime: "14400"
        private_ip: "string_value"
        id: "c970e730-6bc5-44c2-a2bf-8dd1382ffb5f"
        mgmt_ip_address: "10.102.40.59"
        ipv6_address: "2001:cdba:0000:0000:0000:0000:3257:9652"
        partition_id: "5"
        license_edition: "Platinum"
        cpu_license_type: "0"
        cpufrequncy: "1904"
        plt_bw_available: "0"
        device_family: "ns"
        location: "DC12"
        template_interval: "60"
        contactperson: "jane"
        ha_sync: "ENABLED"
        public_ip: "string_value"
        ha_ip_address: "10.102.40.61"
        bmcrevision: "-NA-"
        type: "nsvpx"
        status: "Instance not reachable"
        internal_annotation: "mark_for_delete"
        systemname: "NetScalerBLR1"
        geo_location: "string_value"
        node_id: "a2f7a85e-f388-4d2d-ae0e-646b4f66797e"
        isolation_policy: "shared"
        ip_address: "10.102.40.60"
        provision_request_id: "48f867d1-3d10-4bfa-8498-604a57e67bc5"
        ping_state: "integer_value"
        httpxforwardedfor: "ENABLED"
        std_bw_total: "0"
        display_name: "10.102.40.60-10.102.40.61"
        ami_id: "string_value"
        httpcookie: "ENABLED"
        plt_bw_config: "0"
        partition_name: "p1"
        agent_id: "38f867d1-3d10-4bfa-8498-604a57e67bc4"
        sslvpn_total: "0"
        serialnumber: "HE2H91SCZ6"
        peer_device_ip: "10.102.40.26"
        parent_inventory: "boolean_value"
        profile_password: "nsroot"
        register_failed_device: "false"
        act_id: "fce5b825-9217-4e58-b80c-48cfe8f0c6b3"
        file_name: "instancelist.txt"
        do_instance_config: "true"
        profile_username: "nsroot"
        default_password: "string_value"
        file_location_path: "C:\\myfiles"
        sync_operation: "true"
        peer_host_device_ip: "10.102.40.27"
        device_host_ip: "10.102.40.25"
        tr_task_id: "string_value"
        entity_tag: "[{\"prop_key\":\"country\",\"prop_value\":\"US\"},{\"prop_key\":\"Labcode\",\"prop_value\":\"FtLAB23005\"}]}"
        force_password_change: "false"

  modifymanaged_deviceRequest:
    type: object
    required:
      - managed_device
    properties:
      managed_device:
        $ref: '#/definitions/managed_device_readwrite'
    title: modifymanaged_deviceRequest
    example:
      managed_device:
        std_bw_config: "0"
        description: "Provisioned on 10 Jan 18"
        vcpu_config: "0"
        ent_bw_config: "0"
        datacenter_id: "ec523330-b31e-4831-8c8c-cdb5b9ce4599"
        instance_config: "0"
        is_managed: "true"
        profile_name: "ns_nsroot_profile"
        servicepackage: "svcpkg1"
        license_edition: "Platinum"
        isolation_policy: "shared"
        ip_address: "10.102.40.60"
        plt_bw_config: "0"
        agent_id: "38f867d1-3d10-4bfa-8498-604a57e67bc4"
        peer_device_ip: "10.102.40.26"
        file_name: "instancelist.txt"
        file_location_path: "C:\\myfiles"
        peer_host_device_ip: "10.102.40.27"
        device_host_ip: "10.102.40.25"
        entity_tag: "[{\"prop_key\":\"country\",\"prop_value\":\"US\"},{\"prop_key\":\"Labcode\",\"prop_value\":\"FtLAB23005\"}]}"

  modifymanaged_deviceResponse:
    type: object
    required:
      - managed_device
    properties:
      managed_device:
        $ref: '#/definitions/managed_device'
    title: modifymanaged_deviceResponse
    example:
      managed_device:
        instance_classifier: "0"
        subnet_id: "string_value"
        manufacturedate: " 2/17/2009"
        is_grace: "false"
        hostname: "ADC16_Devlab"
        std_bw_config: "0"
        gateway_deployment: "false"
        is_fips_pooled_license_type: "0"
        gateway_ipv6: "FE80::1"
        ha_master_state: "Primary"
        instance_available: "0"
        vpc_id: "string_value"
        device_finger_print: "string_value"
        instance_state: "Up"
        httpquerywithurl: "ENABLED"
        region: "string_value"
        reason: "Authentication failure"
        ent_bw_available: "0"
        description: "Provisioned on 10 Jan 18"
        is_autoscale_group: "false"
        geo_support: "false"
        is_pooled_license: "false"
        upsince: "Fri Jan 10 09:44:56 2019"
        sslvpn_config: "0"
        security_group: "string_value"
        private_dns: "string_value"
        user_driven: "true"
        zone: "string_value"
        mastools_version: "13.0-49.32"
        model_id: "100000"
        sysservices: "72"
        ent_bw_total: "0"
        vcpu_config: "0"
        tenant_id: "7ed7946f-4af7-11e9-99d2-b6fe81a85d18"
        device_uuid: "1fa7946f-4af7-11e9-99d2-b6fe81a85d08"
        do_config: "true"
        autoprovisioned: "false"
        ent_bw_config: "0"
        datacenter_id: "ec523330-b31e-4831-8c8c-cdb5b9ce4599"
        host_id: "b6fe81a85d08"
        version: "NetScaler NS12.1: Build 54.13.nc"
        instance_config: "0"
        is_managed: "true"
        discovery_time: "number_value"
        instance_mode: "Primary"
        public_dns: "string_value"
        instance_total: "0"
        is_ha_configured: "true"
        trust_id: "2ca7946f-4af7-11e9-99d2-b6fe81a85d09"
        ipv4_address: "10.102.40.60"
        instance_type: "string_value"
        profile_name: "ns_nsroot_profile"
        seq_no: "number_value"
        std_bw_available: "0"
        sysid: "450000"
        servicepackage: "svcpkg1"
        last_updated_time: "number_value"
        cloud: "string_value"
        encoded_serialnumber: "98310000cb254307ee78"
        instance_unique_id: "38f867d1-3d10-4bfa-8498-604a57e67bc4"
        plt_bw_total: "0"
        uptime: "14400"
        private_ip: "string_value"
        id: "c970e730-6bc5-44c2-a2bf-8dd1382ffb5f"
        mgmt_ip_address: "10.102.40.59"
        ipv6_address: "2001:cdba:0000:0000:0000:0000:3257:9652"
        partition_id: "5"
        license_edition: "Platinum"
        cpu_license_type: "0"
        cpufrequncy: "1904"
        plt_bw_available: "0"
        device_family: "ns"
        location: "DC12"
        template_interval: "60"
        contactperson: "jane"
        ha_sync: "ENABLED"
        public_ip: "string_value"
        ha_ip_address: "10.102.40.61"
        bmcrevision: "-NA-"
        type: "nsvpx"
        status: "Instance not reachable"
        internal_annotation: "mark_for_delete"
        systemname: "NetScalerBLR1"
        geo_location: "string_value"
        node_id: "a2f7a85e-f388-4d2d-ae0e-646b4f66797e"
        isolation_policy: "shared"
        ip_address: "10.102.40.60"
        provision_request_id: "48f867d1-3d10-4bfa-8498-604a57e67bc5"
        ping_state: "integer_value"
        httpxforwardedfor: "ENABLED"
        std_bw_total: "0"
        display_name: "10.102.40.60-10.102.40.61"
        ami_id: "string_value"
        httpcookie: "ENABLED"
        plt_bw_config: "0"
        partition_name: "p1"
        agent_id: "38f867d1-3d10-4bfa-8498-604a57e67bc4"
        sslvpn_total: "0"
        serialnumber: "HE2H91SCZ6"
        peer_device_ip: "10.102.40.26"
        parent_inventory: "boolean_value"
        profile_password: "nsroot"
        register_failed_device: "false"
        act_id: "fce5b825-9217-4e58-b80c-48cfe8f0c6b3"
        file_name: "instancelist.txt"
        do_instance_config: "true"
        profile_username: "nsroot"
        default_password: "string_value"
        file_location_path: "C:\\myfiles"
        sync_operation: "true"
        peer_host_device_ip: "10.102.40.27"
        device_host_ip: "10.102.40.25"
        tr_task_id: "string_value"
        entity_tag: "[{\"prop_key\":\"country\",\"prop_value\":\"US\"},{\"prop_key\":\"Labcode\",\"prop_value\":\"FtLAB23005\"}]}"
        force_password_change: "false"

  managed_device_readwrite:
    type: object
    properties:
      std_bw_config:
        description: "Standard Bandwidth running"
        type: integer
        format: int32
      description:
        description: "Description of managed device"
        type: string
        format: string
        minLength: 1
        maxLength: 512
      vcpu_config:
        description: "Number of vCPU allocated for the device"
        type: integer
        format: int32
      ent_bw_config:
        description: "Enterprise Bandwidth configured"
        type: integer
        format: int32
      datacenter_id:
        description: "Datacenter Id is system generated key for data center"
        type: string
        format: uuid
      instance_config:
        description: "Instance license running"
        type: integer
        format: int32
      is_managed:
        description: "Is Managed"
        type: boolean
        format: boolean
      profile_name:
        description: "Device Profile Name that is attached with this managed device"
        type: string
        format: string
        minLength: 1
        maxLength: 128
      servicepackage:
        description: "Service Package Name of the device"
        type: string
        format: string
      license_edition:
        description: "Edition of instance"
        type: string
        format: string
      isolation_policy:
        description: "Isolation Policy of the Device"
        type: string
        format: string
      ip_address:
        description: "IP Address for this managed device"
        type: string
        format: ipaddress
        minLength: 1
        maxLength: 64
      plt_bw_config:
        description: "Platinum Bandwidth configured"
        type: integer
        format: int32
      agent_id:
        description: "Agent Id"
        type: string
        format: uuid
      peer_device_ip:
        description: "Peer Device IP address for instance of type BLX ADC."
        type: string
        format: ipaddress
        minLength: 1
        maxLength: 64
      file_name:
        description: "File name which contains comma separated instances to be  discovered"
        type: string
        format: string
        minLength: 1
        maxLength: 128
      file_location_path:
        description: "File Location on Client for upload/download"
        type: string
        format: string
        minLength: 1
      peer_host_device_ip:
        description: "Peer Host Device IP Address for instance of type BLX ADC."
        type: string
        format: ipaddress
        minLength: 1
        maxLength: 64
      device_host_ip:
        description: "Device Host IP Address for instance of type BLX ADC."
        type: string
        format: ipaddress
        minLength: 1
        maxLength: 64
      entity_tag:
        type: array
        items:
          $ref: '#/definitions/property_map_readwrite'

  managed_device:
    allOf:
      -
        properties:
          id:
            description: Id is system generated key for all the managed devices
            type: string
            format: uuid
          manufacturedate:
             description: "Manufacture Date"
             type: string
             format: date
          hostname:
             description: "Assign hostname to managed device, if this is not provided, name will be set as host name "
             type: string
             format: hostname
             minLength: 1
             maxLength: 256
          is_fips_pooled_license_type:
             description: "FIPS BW license : 0 = No FIPS BW License, 1 = FIPS BW Pool license"
             type: integer
             format: int32
          gateway_ipv6:
             description: "Gateway IPv6 Address"
             type: string
             format: ipv6
          ha_master_state:
             description: "Master State (Primary/Secondary)"
             type: string
             format: string
             minLength: 1
             maxLength: 32
          instance_available:
             description: "Instance license available"
             type: integer
             format: int32
          instance_state:
             description: "State of device, UP only if device accessible"
             type: string
             format: string
             minLength: 1
             maxLength: 64
          httpquerywithurl:
             description: "URL query params flag."
             type: string
             format: string
             minLength: 1
             maxLength: 10
          reason:
             description: "Reason of failure for this managed device"
             type: string
             format: string
             minLength: 1
             maxLength: 1024
          ent_bw_available:
             description: "Enterprise Bandwidth configured"
             type: integer
             format: int32
          upsince:
             description: "Upsince of managed device"
             type: string
             format: date-time
             minLength: 1
             maxLength: 128
          mastools_version:
             description: "Mastools version if the device is embedded agent"
             type: string
             format: string
          model_id:
             description: "Device Model Id"
             type: string
             format: string
             minLength: 1
             maxLength: 64
          sysservices:
             description: "System Services"
             type: number
             format: int64
          ent_bw_total:
             description: "Enterprise Bandwidth Total"
             type: integer
             format: int32
          tenant_id:
             description: "Tenant ID"
             type: string
             format: uuid
             minLength: 1
             maxLength: 128
          device_uuid:
             description: "Device UUID"
             type: string
             format: uuid
          autoprovisioned:
             description: "Device is auto-provisioned or not"
             type: boolean
             format: boolean
          host_id:
             description: "Host ID"
             type: string
             format: string
          version:
             description: "Device Version"
             type: string
             format: string
             minLength: 1
             maxLength: 256
          instance_mode:
             description: "Denotes state- primary,secondary,clip,clusternode"
             type: string
             format: string
          instance_total:
             description: "Instance license"
             type: integer
             format: int32
          is_ha_configured:
             description: "Is HA configured"
             type: boolean
             format: boolean
          trust_id:
             description: "Device ID obtained from trust service"
             type: string
             format: uuid
          ipv4_address:
             description: "IPv4 Address"
             type: string
             format: ipv4
             minLength: 1
             maxLength: 64
          std_bw_available:
             description: "Standard Bandwidth Available"
             type: integer
             format: int32
          sysid:
             description: "System ID"
             type: string
             format: string
          encoded_serialnumber:
             description: "Encoded Serial Number"
             type: string
             format: string
             minLength: 1
             maxLength: 64
          plt_bw_total:
             description: "Total Platinum Bandwidth"
             type: integer
             format: int32
          uptime:
             description: "Uptime of device"
             type: string
             format: int32
             minLength: 1
             maxLength: 128
          mgmt_ip_address:
             description: "Management IP Address for this Managed Device"
             type: string
             format: ipaddress
             minLength: 1
             maxLength: 64
          ipv6_address:
             description: "IPv6 Address"
             type: string
             format: ipv6
          partition_id:
             description: "ID of admin partition"
             type: string
             format: int32
          cpu_license_type:
             description: "VCPU license 0 = No VCPU License, 1 = VCPU Pool license"
             type: integer
             format: int32
          cpufrequncy:
             description: "CPU Frequency (MHZ)"
             type: integer
             format: int32
          plt_bw_available:
             description: "Platinum Bandwidth Available"
             type: integer
             format: int32
          device_family:
             description: "Device Family"
             type: string
             format: string
             minLength: 1
             maxLength: 64
          location:
             description: "Device Location"
             type: string
             format: string
             minLength: 1
             maxLength: 127
          template_interval:
             description: "Template refresh interval"
             type: integer
             format: int32
          contactperson:
             description: "Device contact person"
             type: string
             format: string
             minLength: 1
             maxLength: 64
          ha_sync:
             description: "HA Synchronization State"
             type: string
             format: string
             minLength: 1
             maxLength: 64
          ha_ip_address:
             description: "Peer IP Address"
             type: string
             format: ipaddress
             minLength: 1
             maxLength: 64
          bmcrevision:
             description: "BMC Firmware Version"
             type: string
             format: string
          type:
             description: "Type of device, (Xen | NS)"
             type: string
             format: string
             minLength: 1
             maxLength: 64
          status:
             description: "Status of managed device"
             type: string
             format: string
             minLength: 1
             maxLength: 64
          systemname:
             description: "Device System Name"
             type: string
             format: string
             minLength: 1
             maxLength: 64
          httpxforwardedfor:
             description: "HTTP x-Forwardedfor header flag."
             type: string
             format: string
             minLength: 1
             maxLength: 10
          std_bw_total:
             description: "Standard Bandwidth"
             type: integer
             format: int32
          display_name:
             description: "Display Name for this managed device. For HA pair it will be A-B, and for Cluster it will be CLIP"
             type: string
             format: string
             minLength: 1
             maxLength: 128
          httpcookie:
             description: "Cookie-Header flag."
             type: string
             format: string
             minLength: 1
             maxLength: 10
          partition_name:
             description: "Citrix ADC Admin Partition Name"
             type: string
             format: string
             maxLength: 512
          serialnumber:
             description: "Device Serial Number"
             type: string
             format: string
             minLength: 1
             maxLength: 64
      - $ref: '#/definitions/managed_device_readwrite'

  property_map_readwrite:
    type: object
    properties:
      prop_value:
        description: "Property value"
        type: string
        format: string
        minLength: 1
        maxLength: 512
      prop_key:
        description: "Property key"
        type: string
        format: string
        minLength: 1
        maxLength: 128

  property_map:
    allOf:
      - $ref: '#/definitions/property_map_readwrite'

  Done:
    properties:
      errorcode:
        type: number
        format: int32
        example: 0
      errormessage:
        type: string
        format: string
        example: "Done"
  Error:
    properties:
      errorcode:
        type: number
        format: int32
        example: 1001
      errormessage:
        type: string
        format: string
        example: "id cannot be found"
